Update JavaScript build process to work better with Gutenberg
10up/classifai pull request #209
Opened 2020-03-27 17:42 UTC by ryanwelcher

- [ ] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues

### Changelog Entry

2020-03-27 17:46 UTC, nicholasio commented on .eslintrc
> +	"extends": "@10up/eslint-config",
@ryanwelcher Can you try using the new eslint config? https://github.com/10up/eslint-config/pull/17 It's still being worked on but you can already install it with `npm install @10up/eslint-config@next` there's a Gutenberg specific config

Any feedback is appreciated.

2020-04-01 17:52 UTC, nicholasio commented on src/js/admin.js
> +	if ($toggler === null) return;
This if check is actually not needed. Line 6 already takes care of it.

2020-04-01 17:55 UTC, nicholasio requested changes
@ryanwelcher I updated the eslint config to address some of the issues here. I've also renamed the config name from `10up/eslint-config/gutenberg` to `10up/eslint-config/wordpress` as it makes more sense.

2020-04-01 17:55 UTC, nicholasio commented on src/js/admin.js
> +	if ($toggler === null) return;
This if check is not needed. See Line 6

2020-04-01 17:55 UTC, nicholasio commented on src/js/admin.js
> +	const [$passwordFieldTitle] = document // eslint-disable-line
If you remove Line 14 you don't need to ignore these two lines.

2020-04-01 17:55 UTC, nicholasio commented on src/js/editor.js
> +import { subscribe, select, dispatch } from '@wordpress/data'; // eslint-disable-line
I've updated the eslint config to account for "@wordpress" imports.

2020-04-01 17:55 UTC, nicholasio commented on .eslintrc
> +	"extends": "@10up/eslint-config/gutenberg",
Change to `@10up/eslint-config/wordpress`

2020-04-01 17:55 UTC, nicholasio commented on package.json
> +    "@10up/eslint-config": "^2.0.0-next",
Update to `2.0.2-next`

2020-09-29 15:40 UTC, helen commented
Could I get a summary here about why we're using the 10up config instead of `wp-scripts`? I am not strongly opinionated except that I am not sure why there is a WP-specific config inside 10up's package when a WP one already exists.

2020-10-21 17:52 UTC, jeffpaul commented
@helen @ryanwelcher @nicholasio @dinhtungdu @dkotter given that we're adding a Gutenberg integration as part of #228 do we want to revisit this PR and bring into the 1.6.0 release if it'll help in relation to the work in 228?

2020-10-22 04:28 UTC, dinhtungdu commented
@jeffpaul I prefer to keep this one for 1.7 because it's not a blocker for 228.

2021-07-12 13:44 UTC, ryanwelcher commented
@dinhtungdu @jeffpaul based on the changes to our tooling since this PR was created, I would probably recommend removing the custom webpack config in favor of using everything provided by [10up-toolkit](https://github.com/10up/10up-toolkit). 

This is the [standard approach for new projects ](https://github.com/10up/wp-scaffold/blob/trunk/themes/10up-theme/package.json)and provides all of the linting tools we'd need here. 

Additionally, [we can leverage the package.json file](https://github.com/10up/wp-scaffold/blob/trunk/themes/10up-theme/package.json#L23) to manage customizations which means that we won't need a custom webpack config file

2021-08-24 22:14 UTC, helen commented
I'm closing this out for now, it's so out of date we are better off starting over again. I am not yet sure about 10up-toolkit for OSS WP plugins, as there are differences between something that happens to be openly available but still geared toward client work, and what we want to represent in a community project. We need to take a look at this across 10up plugins and then go from there :)

2021-08-24 22:14 UTC, closed without merging