Allow filtering of the image URL prior to generating image tags and alternate text
10up/classifai pull request #217
Opened 2020-07-17 15:18 UTC by petenelson

### Description of the Change
In instances where an image has been offloaded to a CDN, running the `image` CLI command is failing. This command calls `generate_image_alt_tags()`, which calls `get_largest_acceptable_image_url()`, which requires an image to be physically present on the server. If the image is not present, the image URL is null and no tags or alternate text can be generated. 

### Alternate Designs

None

### Benefits

This pull request adds a filter to allow overriding of the image URL which can allow the Computer Vision API to pull the image directly from a CDN.

### Possible Drawbacks

None

### Verification Process

No verification was performed.

### Checklist:

- [X] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Changelog Entry

* Added `classifai_generate_image_alt_tags_source_url` filter to allow overriding of the image URL within `generate_image_alt_tags()`

2020-07-17 15:51 UTC, jeffpaul commented
This may resolve #201, but testing will be needed to be certain.

2020-07-20 14:44 UTC, dinhtungdu requested changes

2020-07-20 14:44 UTC, dinhtungdu commented on includes/Classifai/Providers/Azure/ComputerVision.php
> +			if ( ! empty( $image_url ) ) {
This should check if `$image_url` is empty or an invalid URL.
```suggestion
			if ( empty( $image_url ) || ! filter_var( $image_url, FILTER_VALIDATE_URL ) ) {
```

2020-07-23 11:41 UTC, dinhtungdu requested changes

2020-07-23 11:41 UTC, dinhtungdu commented on includes/Classifai/Providers/Azure/ComputerVision.php
> +			if ( ! empty( $image_url ) || ! filter_var( $image_url, FILTER_VALIDATE_URL ) ) {
This should be `empty( $image_url )` but not `! empty( $image_url )`.

Currently, `$image_url` will be `null` if `classifai_generate_image_alt_tags_source_url` is not used. Besides, if we use that filter, the function will get the image URL again.

2020-07-24 03:22 UTC, dinhtungdu approved these changes
LGTM 👍

2020-07-24 20:57 UTC, merged