Fix/fold wp cli into hookdocs site
10up/classifai pull request #312
Opened 2021-10-06 14:50 UTC by ActuallyConnor

### Description of the Change

- Port our WP-CLI commands docs into the hookdoc site
- Rename it to ClassifAI Developer Documentation (like what ElasticPress does). 
- Add a simple reference in the README.md

### Alternate Designs

### Benefits

### Possible Drawbacks

### Verification Process

### Checklist:

- [ ] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues

### Changelog Entry

2021-10-07 09:19 UTC, faisal-alvi requested changes

2021-10-07 09:19 UTC, faisal-alvi commented on README.md
Please also remove the "**ClassifAI Settings Commands**" section as it is also covered in the docs. The next title after the "Check out.." line should be "Frequently Asked Questions".

2021-10-07 09:19 UTC, faisal-alvi commented on README.md
> +
This line is not required. It's already added below. Please remove from here.

2021-10-07 09:19 UTC, faisal-alvi commented on README.md
> +- Check out the [ClassifAI docs](https://10up.github.io/ClassifAI/).
The link path is case-sensitive. Please change `ClassifAI` to `classifai`

2021-10-07 09:19 UTC, faisal-alvi commented on README.md
> +- Check out the [ClassifAI docs](https://10up.github.io/ClassifAI/).
The link path is case-sensitive. Please change `ClassifAI` to `classifai`

2021-10-07 20:16 UTC, ActuallyConnor commented
@faisal-alvi all the requested changes should be made now 😃

2021-10-08 13:57 UTC, faisal-alvi approved these changes

2021-10-08 16:13 UTC, merged

2021-10-08 16:18 UTC, ActuallyConnor commented
@faisal-alvi @jeffpaul any possibility we could add the Hacktoberfest tag to the issue?

2021-10-08 16:20 UTC, jeffpaul commented
@ActuallyConnor sure, let me do that, though not sure if Digital Ocean will count it after the fact but worth a shot!

2021-10-08 18:37 UTC, ActuallyConnor commented
It worked 👍