feat/193: add a previewer in admin settings
10up/classifai pull request #351
Opened 2022-07-03 18:36 UTC by Sidsector9

### Description of the Change

This PR adds a feature to display preview of the taxonomy types for a post.

1. Adds a select dropdown with AJAX-based search input field to select/search a post.
2. Displays the score/relevance and the label in results.
3. Displays color-based bar with a width indicating score for visual clarity.

Closes #193 

### Screencast

https://user-images.githubusercontent.com/17757960/177052864-842194a2-630f-4702-b2fa-5898b9a34558.mov

### Checklist:

- [ ] I have read the [**CONTRIBUTING**](https://github.com/10up/.github/blob/trunk/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Changelog Entry
Added: Preview for NLU settings

### Credits

Props @Sidsector9

2022-07-03 18:37 UTC, Sidsector9 commented
@jeffpaul What title should we add to the previewer? Also wanted your opinion on the results, is there anything we would want to add/remove in this implementation?

2022-07-06 21:17 UTC, jeffpaul commented
>What title should we add to the previewer?
How about `Preview Language Processing`?

>Also wanted your opinion on the results, is there anything we would want to add/remove in this implementation?
It might help to show placeholders for the Categories, Keywords, Entities, and Concepts sections where data eventually gets returned/rendered so that section doesn't suddenly jump down when the data's ready?

2022-07-15 05:18 UTC, iamdharmesh requested changes
Thanks a lot for the great work here @Sidsector9. Overall code looks good to me, just added a few minor comments to check. 
Also, please help to add title as mentioned here https://github.com/10up/classifai/pull/351#issuecomment-1176757894

Thanks

2022-07-15 05:18 UTC, iamdharmesh commented on includes/Classifai/Admin/PreviewClassifierData.php
> +		add_action( 'wp_ajax_get_post_search_results', array( $this, 'get_post_search_results' ) );
Probably better to add a prefix here in ajax action to prevent the risk of conflict with other plugins if they are using  `get_post_search_results`.

2022-07-15 05:18 UTC, iamdharmesh commented on includes/Classifai/Admin/PreviewClassifierData.php
> +		$post_statuses = isset( $_POST['post_statuses'] ) ? explode( '/', sanitize_text_field( $_POST['post_statuses'] ) ) : 'publish';
Post search not working, maybe some issue with the separator? working fine after updating code like below.
```suggestion
		$post_types    = isset( $_POST['post_types'] ) ? explode( ',', sanitize_text_field( $_POST['post_types'] ) ) : 'post';
		$post_statuses = isset( $_POST['post_status'] ) ? explode( ',', sanitize_text_field( $_POST['post_status'] ) ) : 'publish';
```

2022-07-15 05:18 UTC, iamdharmesh commented on src/js/admin.js
> +import Choices from 'choices.js';
Do we need twice import of `choices.js` here?

2022-07-17 19:08 UTC, Sidsector9 commented
### Empty placeholders added:

<img width="1792" alt="Screenshot 2022-07-18 at 12 25 47 AM" src="https://user-images.githubusercontent.com/17757960/179420695-2c63abfd-0d4c-4eb0-b1b1-3eff9fe1525d.png">

### With results populated:


<img width="1792" alt="Screenshot 2022-07-18 at 12 38 14 AM" src="https://user-images.githubusercontent.com/17757960/179421112-5487b3dc-2476-4dcb-80fc-c2d6758d61bb.png">

2022-07-19 15:37 UTC, iamdharmesh approved these changes
LGTM! :rocket: Thanks for great work here @Sidsector9

2022-07-20 20:47 UTC, merged