#430: Use proper plurals based on image settings
10up/classifai pull request #482
Opened 2023-06-08 14:17 UTC by jamesmorrison

### Description of the Change
Adds singular labels where a single image is selected for generation.

Closes #430

### How to test the Change

**Test 1: Plural**:
- Open Classifai settings:
  - set the number of images to generate between 2 - 10 (i.e. not 1)
  - Check / ensure: `Enable image generation` is checked
- Create a new post:
  - Open the media modal (in a new post => featured image / media block) and select `Generate Images`
  - Confirm the text remains as:
    - `Enter a prompt below to generate images.`
    - `Once images are generated, choose one or more of those to import into your Media Library and then choose one image to insert.`

**Test 3: Singular**:
- Open Classifai settings:
  - set the number of images to generate 1 (i.e. not 2 - 10)
  - Check / ensure: `Enable image generation` is checked
- Create a new post:
  - Open the media modal (in a new post => featured image / media block) and select `Generate Images`
  - Confirm the text shows singular terminology:
    - `Enter a prompt below to generate an image.` - new
    - `Once an image is generated, you can import it into your Media Library and then select to insert.` - new

### Changelog Entry
> Added - Add singular labels when a single image is selected for generation.

### Credits
Props @jamesmorrison

### Checklist:
- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2023-06-08 14:18 UTC, jamesmorrison commented
@jeffpaul / @dkotter Please could you review this change? If you'd prefer alternative singular test, please let me know what this should be updated to - I added what I thought was appropriate here.

2023-06-08 14:52 UTC, ravinderk requested changes

2023-06-08 14:52 UTC, ravinderk commented on includes/Classifai/Providers/OpenAI/DallE.php
> +					if ( $number_of_images > 1 ) {
We can use [`_n`](https://developer.wordpress.org/reference/functions/_n/) function to handle plural translation.

2023-06-08 14:52 UTC, ravinderk commented on includes/Classifai/Providers/OpenAI/DallE.php
> +					if ( $number_of_images > 1 ) {
We use [`_n`](https://developer.wordpress.org/reference/functions/_n/) function to handle plural translation.

2023-06-15 12:16 UTC, jamesmorrison commented on includes/Classifai/Providers/OpenAI/DallE.php
> +					if ( $number_of_images > 1 ) {
Thanks @ravinderk; I've updated this.

2023-06-15 12:16 UTC, jamesmorrison commented on includes/Classifai/Providers/OpenAI/DallE.php
> +					if ( $number_of_images > 1 ) {
Thanks @ravinderk; I've updated this.

2023-06-15 19:10 UTC, dkotter commented on includes/Classifai/Providers/OpenAI/DallE.php
> +					if ( $number_of_images > 1 ) {
Apologies for not seeing this sooner but I don't think this is the approach we should take. While it is cleaner, some languages use the singular form for numbers other than 1 (see https://codex.wordpress.org/I18n_for_WordPress_Developers#Plurals). I suggest we go back to the original approach [here](https://github.com/10up/classifai/pull/482/commits/d097367e5c51bfc3d16ff86a3eeed76538c632cf)

2023-06-15 19:13 UTC, dkotter commented
@jamesmorrison Thanks for the work here! I've left one comment that I think we should address. There's also a few other text strings that we probably want to update.

- The `Generate images` tab text: https://github.com/10up/classifai/blob/develop/includes/Classifai/Providers/OpenAI/DallE.php#L126
- The `Generate images` button text: https://github.com/10up/classifai/blob/develop/includes/Classifai/Providers/OpenAI/DallE.php#L150
- Text shown after an image is generated: https://github.com/10up/classifai/blob/develop/includes/Classifai/Providers/OpenAI/DallE.php#L154

2023-07-05 09:01 UTC, jamesmorrison commented on includes/Classifai/Providers/OpenAI/DallE.php
> +					if ( $number_of_images > 1 ) {
@dkotter Ok, I've reverted this.

2023-07-05 09:03 UTC, jamesmorrison commented
@dkotter I've reverted to if else (rather than `_n()`) and added singular text where this was missed previously. I've tested and confirmed this works; please could you check this?

2023-07-06 14:31 UTC, dkotter approved these changes

2023-07-06 14:32 UTC, merged