#486 - Optimize calls to Microsoft Azure Text to Speech API
10up/classifai pull request #487
Opened 2023-06-14 18:49 UTC by joshuaabenazer

### Description of the Change

Closes #486 

### How to test the Change

1. Create a new post on the post type that supports the Microsoft Azure Text to Speech feature.
2. Publish the post. This should also generate the audio file for the post.
3. In a new tab head over to the media library and edit the audio file for the post that got recently created. Should be the first in the list.
4. Now update the post once again without any changes. Upon refresh of the edit screen of the audio file opened in point 3  above should **not show an error** of post does not exist. This confirms that the file was not re-generated again.
5. Now make changes to content or title of the post and update again. Upon refresh of the edit screen of the audio file opened in point 3  above should **now show an error** of the post not existing anymore. This confirms that the file was re-generated due to update in post content or title.
6. Checking the media library again an updated audio file should be visible.

### Changelog Entry

> Changed - Optimized calls to Microsoft Azure Text to Speech API

### Credits

Props @joshuaabenazer 

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2023-06-15 19:22 UTC, dkotter requested changes

2023-06-15 19:22 UTC, dkotter commented on includes/Classifai/Admin/SavePostHandler.php
> +		if ( ! empty( $content_hash ) ) {
Seems like we may want a check here to ensure the `$saved_attachment_id` actually exists, in case this was deleted somehow. We could also combine this `if` statement into a single line:
```suggestion
		if ( ! empty( $content_hash ) && md5( $post_content ) === $content_hash && $saved_attachment_id  ) {
```

2023-06-15 19:22 UTC, dkotter commented on includes/Classifai/Admin/SavePostHandler.php
> +		if ( ! empty( $content_hash ) ) {
I would also maybe add a comment above this `if` statement describing what we're doing. Something like:
```php
// Don't regenerate the audio file it it already exists and the content hasn't changed.
```

2023-06-20 14:13 UTC, joshuaabenazer commented
@dkotter just noticed that if the audio attachment is deleted accidentally from the media library, this update would make it such that no new audio would be generated unless we deleted the audio id meta from the post. Thinking of taking care of that as part of this PR. Thoughts?

2023-06-20 21:14 UTC, dkotter approved these changes

2023-06-20 21:15 UTC, dkotter commented
> just noticed that if the audio attachment is deleted accidentally from the media library, this update would make it such that no new audio would be generated unless we deleted the audio id meta from the post. Thinking of taking care of that as part of this PR. Thoughts?

Looks like you took care of that here, is that correct? If so, I think this is good to go

2023-06-21 04:37 UTC, joshuaabenazer commented
> Looks like you took care of that here, is that correct? If so, I think this is good to go
@dkotter yes that is correct. Let me know if there is anything further that I need to do on this. Thanks.

2023-06-21 10:51 UTC, ravinderk reviewed
@joshuaabenazer Do we skip an audio generation when "Generate audio for this post" is set to `no` during bulk action or WP CLI command? If not, can we optimize this too?

2023-06-21 16:53 UTC, dkotter commented
> @joshuaabenazer Do we skip an audio generation when "Generate audio for this post" is set to `no` during bulk action or WP CLI command? If not, can we optimize this too?

I don't believe we do but I also think that is by design. If someone manually is triggering this via the bulk actions or via our WP-CLI command, I think that should bypass that option. That is just my opinion though, happy to discuss that but I'd suggest that should be handled in a separate issue.

2023-06-21 16:54 UTC, merged