Draft: Added Generate Excerpt for the Classic Editor.
10up/classifai pull request #491
Opened 2023-06-15 17:12 UTC by jamesmorrison

**Note: this is not yet ready for code review**

### Description of the Change
Adds the Excerpt Generation (introduced in https://github.com/10up/classifai/pull/405 for Gutenberg) to the classic editor.

Closes #417

### How to test the Change

1. Create a post using the classic editor
2. Add some content and save as a draft (note: a draft must be saved as we need a post ID to make the OpenAI request)
3. Locate the excerpt box and click "Generate excerpt"
4. Button should be disabled; content should be added to the excerpt `textarea`; button text is updated (to Re-generate excerpt); button should be enabled.

### Changelog Entry
> Added - Excerpt Generation for the classic editor

### Credits
Props @jamesmorrison 

### Checklist:
- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2023-07-20 14:56 UTC, ravinderk requested changes
@jamesmorrison, Can you resolve code conflicts?

2023-08-10 18:26 UTC, ravinderk commented
@dkotter This pull request is ready for review.

2023-08-17 20:54 UTC, dkotter approved these changes, later dismissed

2023-08-17 21:37 UTC, dkotter approved these changes

2023-08-17 21:37 UTC, merged