feat/488: Ability to resize post content using OpenAI's ChatGPT
10up/classifai pull request #532
Opened 2023-07-12 16:40 UTC by Sidsector9

### Description of the Change

The feature adds the ability to "grow" and "shrink" the paragraph block content. (Watch video below for demo)

- The feature is implemented so as to be consistent with title generation feature using the same service.
- Instead of repeating calls to the API to re-generate the content until it is desirable by the editor, the editor can set the number of suggestions in a single call, and then choose the most desirable suggestion from the modal window, thus providing granular control.
- The modal window shows some additional stats regarding the increase/decrease in word and character count to help the editor make a more informed decision while selecting from the list of suggestions.
- The name and icons for the 2 menu options are not final and is open for suggestions.

### Limitations

- Currently, this feature only works with the paragraph block.
- At a time, it resizes content for a single block at a time. We can iteratively improve this to handle the situation where a a non-paragraph block is between 2 paragraphs.

### What is next?

The next improvement can be resizing content when multiple, consecutive paragraph blocks are selected.

Closes #488

### Screenshot

#### 1. Resizing content settings:

<img width="945" alt="Screenshot 2023-07-12 at 9 53 21 PM" src="https://github.com/10up/classifai/assets/17757960/66069734-e382-4420-8c56-08f2314c829b">

#### 2. Grow content

https://github.com/10up/classifai/assets/17757960/bec85aa0-80fa-49f1-ace4-e3e0b73a422d

#### 3. Shrink content

https://github.com/10up/classifai/assets/17757960/45bf0f2d-f7f9-4250-9496-e491df44c448

### How to test the Change

1. Enable the feature under `/wp-admin/tools.php?page=classifai&tab=language_processing&provider=openai_chatgpt`
2. Go to a post with content

### Changelog Entry

> Added - Ability to resize post content using OpenAI's ChatGPT
> Changed - Bump WordPress minimum from 5.7 to 5.8

### Credits

Props @jeffpaul, @Sidsector9, @dkotter 

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2023-07-13 17:52 UTC, jeffpaul commented
@Sidsector9 I chatted with Jake on this today and agreed the best option would be to add a new block toolbar option using either https://github.com/10up/classifai/blob/develop/assets/img/icon.svg or https://github.com/10up/classifai/blob/develop/assets/img/menu-icon.svg for the toolbar icon and then nesting the expand/reduce options in a dropdown there.

2023-07-13 17:54 UTC, jeffpaul commented
Also, let's remove Subscriber from one of the default enabled roles for this (and maybe Contributor as well?) so that we don't get normal site visitors using up a sites OpenAI budget without an admin explicitly enabling that.

2023-07-17 21:27 UTC, dkotter requested changes

2023-07-17 21:27 UTC, dkotter commented on includes/Classifai/Services/LanguageProcessing.php
> +		return true;
Assuming this was there for test purposes

2023-07-17 21:27 UTC, dkotter commented on includes/Classifai/Services/LanguageProcessing.php
> +				'permission_callback' => [ $this, 'resize_content_permissions_check' ],
We should add an `args` field here and detail out all the various arguments that can be passed in, similar to what we do on other endpoints

2023-07-17 21:27 UTC, dkotter commented on includes/Classifai/Services/LanguageProcessing.php
> +		// Check if title generation is turned on.
This comment needs updated

2023-07-17 21:27 UTC, dkotter commented on src/js/gutenberg-plugins/content-resizing-plugin.js
> +import { store as blockEditorStore, BlockControls } from '@wordpress/block-editor';
Some eslint errors in this file that need addressed

2023-07-17 21:27 UTC, dkotter commented on includes/Classifai/Services/LanguageProcessing.php
> +				'methods'             => WP_REST_Server::EDITABLE,
Does this need to be `EDITABLE` or can we use `CREATABLE`, which will only support `POST` requests?

2023-08-01 15:34 UTC, Sidsector9 commented
As per the 1:1 with @dkotter, we concluded that we can keep the feature what we have now as it is, and maybe separately work on detecting the start of a word if an editor accidentally makes a text selection abruptly. For starters, we can detect space characters before a word to identify the start of the word.

Rest of the review changes are done.

cc: @jeffpaul

2023-08-02 14:25 UTC, ankitguptaindia commented
Hello there, I noticed when utilizing the Grow/Shrink feature with AI-generated content, certain inline styles such as Bold, Italic, Links, and others are being overridden by the newly generated content. This behavior may lead to the loss of important formatting if the author didn't notice and override content.

**More Details-**



https://github.com/10up/classifai/assets/6384299/432eaca4-6cb4-4d5e-80f6-3293622429ab




**Steps to Reproduce:**

1. Access the paragraph that allows using AI to Grow/Shrink content.
2. Apply the Grow/Shrink functionality to the existing content containing inline styles (e.g., Bold, Italic, Links).
3. Observe that the inline styles are replaced or removed in the AI-generated content.
 

**Proposed Solution:**

We can simply add a message in the new content modal so the author will know before importing newly created content by AI. 

**Example:**


![Screenshot 2023-08-02 at 7 52 27 PM](https://github.com/10up/classifai/assets/6384299/b80a0247-5e5b-4238-b3ee-63af0035a0c6)

2023-08-02 17:23 UTC, Sidsector9 commented
@ankitguptaindia that is expected in this implementation as we send plaintext data to ChatGPT and receive in the same format.

2023-08-02 20:27 UTC, dkotter commented on includes/Classifai/Providers/OpenAI/ChatGPT.php
> +						'role'    => 'user',
Wondering if similar to what we just did for our excerpt and title generation features, we should look to use `system` messages here? I may be wrong but that seems like the approach OpenAI suggests and also seems to provide more flexibility (for instance if you want to provide more in-depth instructions)

2023-08-02 20:32 UTC, dkotter commented
Left one minor comment but this looks really good, nice work here @Sidsector9!

Not something we need to change right now but we may want to consider making our prompts a little more specific. Rather than asking to increase or decrease by a small margin, we could ask to increase or decrease by a specified amount (characters, words, lines). I notice right now that sometimes the choices it returns are rather large, so giving it some parameters (increase this content between 2-4 sentences, as an example) may give better results.

2023-08-04 17:05 UTC, dkotter commented on includes/Classifai/Providers/OpenAI/ChatGPT.php
> +						'content' => esc_html( $args['content'] ) . '',
Do we need the extra concatenation here?
```suggestion
						'content' => esc_html( $args['content'] ),
```

2023-08-04 17:05 UTC, dkotter submitted a review, later dismissed

2023-08-04 17:11 UTC, jeffpaul commented
Note that we're waiting on some UX review from @jakemgold before merging/releasing this PR

2023-08-18 08:19 UTC, Sidsector9 commented
## Update

Then changes requested by Jake are added. @jeffpaul as discussed on Slack, this PR is waiting on you for the updated copy to use for the heading and initial sentences.

2023-08-24 19:16 UTC, dkotter commented on includes/Classifai/Providers/OpenAI/ChatGPT.php
> +						'content' => esc_html( $args['content'] ) . '',
@Sidsector9 Just following up again on this one

2023-08-24 19:20 UTC, dkotter requested changes

2023-08-24 19:20 UTC, dkotter commented on src/js/gutenberg-plugins/content-resizing-plugin.js
> +			<p>{ __( 'Click on a row to apply:' ) }</p>
Not sure we need this paragraph. It's not super accurate (you're not clicking on the row but on the button) and I think it's clear enough what you need to do

2023-08-24 19:20 UTC, dkotter commented on src/js/gutenberg-plugins/content-resizing-plugin.js
> +			title={ __( 'Suggestions', 'classifai' ) }
Personal opinion but right now the title of the modal is `Suggestions` and then right below that we show `Suggestion` in the table header. Seems redundant to have these one after the other. Wondering if we should change this title to something else, like `Review Suggestions`, `Choose a Suggestion`, `Review Text`, `Select a Suggestion`

2023-08-24 19:20 UTC, dkotter commented on src/js/gutenberg-plugins/content-resizing-plugin.js
> +		requestAnimationFrame( () => processAnimation( content ) );
Error here because this function isn't defined.

2023-08-24 19:22 UTC, dkotter commented
Left a few suggestions but also saw a couple other things:

1. Getting a deprecation error in the console: `Using custom components as toolbar controls is deprecated since version 5.6. Please use ToolbarItem, ToolbarButton or ToolbarDropdownMenu components instead. See: https://developer.wordpress.org/block-editor/components/toolbar-button/#inside-blockcontrols`
2. E2E test is failing
3. The animation we show when loading results has issues when we select a short paragraph. It expands outside of it's container into the content below. Not a huge deal but would be nice to solve:

<img width="1512" alt="Animation extending outside container" src="https://github.com/10up/classifai/assets/916738/d2f5c0be-670e-4392-9211-582cd4895e6a">

2023-08-25 19:00 UTC, Sidsector9 commented
@dkotter this feature is not working well on WP 6.3 due to major changes in the Block editor. It works fine in WP 6.2. A trick to make this feature work in WP 6.3 is to enable Custom Fields under Preferences > Panels.

I couldn't find a way to fix this, I'm still investigating.

2023-08-25 19:56 UTC, dkotter commented on src/js/gutenberg-plugins/content-resizing-plugin.js
> +			<p>{ __( 'Click on a row to apply:' ) }</p>
So looked at the failing E2E test and the issue was we were clicking on the row, not the button. I've fixed that in [141ea55](https://github.com/10up/classifai/pull/532/commits/141ea558c9ea8c64d0853f58c2effb94f2204fe4) but I guess wondering now if the intention is to allow the user to click on the entire row to insert? Or is clicking on the button good enough?

2023-08-29 20:57 UTC, jeffpaul commented
@Sidsector9 since this isn't a functional issue with the loading animation, perhaps remove that for now and open that in a separate PR to continue iterating on and can land in a 2.3.x minor release.  Also, I confirmed and the existing "Expand this text" and "Condense this text" copy is good for us to ship.

2023-08-31 02:29 UTC, dkotter commented on src/js/gutenberg-plugins/content-resizing-plugin.js
> +			<p>{ __( 'Click on a row to apply:' ) }</p>
@Sidsector9 Just flagging this again. Let me know if this is a feature that we want and just isn't working. Otherwise I'd suggest we remove this text

2023-08-31 21:25 UTC, dkotter commented
@Sidsector9 @jeffpaul Reviewing this again today in hopes of getting this merged and ran into one thing. Right now our E2E test is failing on WordPress 5.7 (our minimum) because we're using a the `ToolbarDropdownMenu` component which wasn't added to core until 5.8.

I can see two paths forward:

1. Find a different approach for that dropdown menu that will work in 5.7+
2. Bump our minimum supported WordPress version to at least 5.8

Not sure how hard the first will be. I'm totally on board to bump our minimums but open to thoughts there.

2023-09-01 07:51 UTC, Sidsector9 commented
@dkotter I've bumped minimum WordPress version from 5.7 to 5.8

2023-09-01 15:00 UTC, dkotter approved these changes

2023-09-01 15:00 UTC, merged