Enhancement/577 Threshold values for Embeddings
10up/classifai pull request #621
Opened 2023-11-23 10:54 UTC by faisal-alvi

### Description of the Change

* This PR adds the threshold setting fields for each taxonomy in the Embeddings settings, allowing users to set the threshold value.
* The default value is set to 75%.
* These calculations are based on https://github.com/10up/classifai/issues/577#issuecomment-1808636943.

Closes #577

### How to test the Change

### Changelog Entry
> Added - Threshold values for Embeddings

### Credits

Props @timatron @dkotter @faisal-alvi 

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2023-11-27 19:55 UTC, dkotter requested changes

2023-11-27 19:55 UTC, dkotter commented on includes/Classifai/Providers/OpenAI/EmbeddingCalculations.php
> +		 */
This hook docblock will need updated to match our other hooks so it ends up in our doc site

2023-11-27 19:55 UTC, dkotter commented on includes/Classifai/Providers/Provider.php
> +			esc_attr( $args['label_for'] ),
Wondering if we need a simple check here to ensure this value actually exists? Something like

```
esc_attr( $args['label_for'] ?? '' )
```

2023-11-27 19:55 UTC, dkotter commented on includes/Classifai/Providers/OpenAI/Embeddings.php
> +		 */
Same comment on this hook docblock

2023-11-27 19:59 UTC, dkotter requested changes
Note that there's some PHPCS warnings that we should look to fix: https://github.com/10up/classifai/actions/runs/6968812438/job/18963465180#step:8:16. Not sure why it's not showing this check as having failed, maybe we only fail on errors and not warnings? But these are easy enough to fix up so ideally we address these

EDIT: looked into this and seems it's due to the 10up-Default ruleset we extend, based on this line: https://github.com/10up/phpcs-composer/blob/master/10up-Default/ruleset.xml#L33

Personally I think we should remove this so we get failures on warnings, otherwise those items never get fixed up.

2023-11-28 10:07 UTC, faisal-alvi commented
@dkotter thanks for the feedback. I've implemented them (and also fixed the minor phpcs warnings). Please check.

> Personally I think we should remove this so we get failures on warnings, otherwise those items never get fixed up.

Agree. Should I raise a PR there?

2023-11-28 21:37 UTC, dkotter commented on includes/Classifai/Providers/OpenAI/EmbeddingCalculations.php
> +		 * @since 2.6.0
```suggestion
		 * @since 2.5.0
```

2023-11-28 21:37 UTC, dkotter commented on includes/Classifai/Providers/OpenAI/Embeddings.php
> +	 * @since 2.6.0
```suggestion
	 * @since 2.5.0
```

2023-11-28 21:38 UTC, dkotter commented on includes/Classifai/Providers/OpenAI/Embeddings.php
> +		 * @since 2.6.0
```suggestion
		 * @since 2.5.0
```

2023-11-28 21:38 UTC, dkotter commented on includes/Classifai/Providers/Provider.php
> +	 * @since 2.6.0
```suggestion
	 * @since 2.5.0
```

2023-11-28 21:53 UTC, dkotter requested changes
In testing, found a few things:

1. When first going to the settings page, I don't see any default values for the thresholds. After saving the first time, they get set to 75% but those should be set on initial load:
![Default values blank](https://github.com/10up/classifai/assets/916738/a5236a83-370b-4619-ba0d-ca3e77bf6026)
2. If the Watson feature is turned off, doesn't seem we load the language-processing.css file, so styles aren't getting loaded:
![Missing styles](https://github.com/10up/classifai/assets/916738/6ad6c68e-0fc8-45dc-846d-f50015523cce)
3. Don't think this is a side-effect of this PR (probably due to changes in #609) but no longer seeing the Classify button if the feature is disabled on the post level:

![Missing button](https://github.com/10up/classifai/assets/916738/38699e6c-c1ad-460f-8e6f-c6bdd4e4c0c4)

2023-11-28 21:53 UTC, dkotter commented
> Agree. Should I raise a PR there?

Yeah, or just make that change in this PR, either way works for me

2023-11-29 12:29 UTC, faisal-alvi commented
Thanks for the feedback. Changes are implemented.

> Don't think this is a side-effect of this PR (probably due to changes in https://github.com/10up/classifai/pull/609) but no longer seeing the Classify button if the feature is disabled on the post level

I have found that this is because the post status is being `auto-draft` on the first load and the plugin can not find it in the allowed post types list.

![image](https://github.com/10up/classifai/assets/25176325/474eadd4-6850-4ecb-9338-a12938e37219)

So as a fix, we can allow `auto-draft` if someone has allowed the `draft` type; no need to add a new post type in the settings.

2023-11-29 17:07 UTC, dkotter requested changes

2023-11-29 17:07 UTC, dkotter commented on includes/Classifai/Providers/Watson/NLU.php
> +		if ( $this->has_access( 'content_classification' ) || isset( $_GET['page'] ) && 'classifai' === $_GET['page'] ) { // phpcs:ignore WordPress.Security.NonceVerification.Recommended
I'm not sure we'll want to add this conditional here. What this means is that even if the NLU feature is off, we register the NLU taxonomies anytime we're on any ClassifAI settings page (as well as load other functionality that isn't needed).

Unless there's something I'm missing, I think we can just take the same `enqueue_admin_assets` method here and load the correct assets in the Embeddings class, to ensure the assets we need are always loaded on that page. If both features are turned on, that's fine, as WordPress can handle the situation where an asset is enqueued twice.

2023-11-29 17:09 UTC, dkotter commented
> I have found that this is because the post status is being auto-draft on the first load and the plugin can not find it in the allowed post types list.

I was testing with an already published item so I don't think that's the issue I was facing. In looking closer, it seems we have a conditional in our `gutenberg-plugin.js` file that only loads that button if NLU is enabled. Seems it was set up this way from the beginning and so that button has never shown for the Embeddings feature (which I was mistaken there, I thought I remember it being there but I guess not). I think it would be nice to show that button but that doesn't need to be handled in this PR.

2023-11-30 19:38 UTC, dkotter approved these changes

2023-12-04 21:40 UTC, berkod approved these changes

2023-12-07 17:13 UTC, merged