fix/708: fixes issue with processing `.png` images with large file sizes.
10up/classifai pull request #754
Opened 2024-04-01 14:18 UTC by Sidsector9

### Description of the Change

This PR:
- sets the image scanning timeout to 60 seconds.
- adds the filter hook `'classifai_ms_computer_vision_scan_image_timeout'`

Closes #708 

### How to test the Change

This can be tested with the following sample images:

[5mb-png-image](https://github.com/10up/classifai/assets/17757960/a92aa3da-bad5-4e36-977d-945789b84f19)
[10mb-png-image](https://github.com/10up/classifai/assets/17757960/77a38862-8c3a-4a00-8407-86284a64cb41)

### Changelog Entry

> Added - filter hook `'classifai_ms_computer_vision_scan_image_timeout'` to increase image processing timeout.
> Fixed - issue with processing `.png` images with large file sizes.

### Credits

Props @QAharshalkadu @Sidsector9 

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2024-04-01 16:40 UTC, dkotter requested changes
One minor change request on the documentation side.

But also a question that may need looked at further. According to the API docs, the max image supported is 4MB. We have some [code in place](https://github.com/10up/classifai/blob/fe28ee7c7971fecdc4de246a5b0beb8b4baf2747/includes/Classifai/Providers/Azure/ComputerVision.php#L742) to return an error if the image size is larger than that so in theory, a 5MB image shouldn't even work, though it sounds like that's not the case.

Some time should be spent here to figure out how images larger than 4MB are making it through and making any needed adjustments. I know we check the file size in the `rest_endpoint_callback` method but maybe that check needs added other places as well?

2024-04-01 16:40 UTC, dkotter commented on includes/Classifai/Providers/Azure/ComputerVision.php
> +				 */
We'll want to ensure this doc block follows the JS Hook standards so it shows properly in our documentation. See the `classifai_should_smart_crop_image` filter in this file for an example

2024-04-02 12:55 UTC, Sidsector9 commented
> According to the API docs, the max image supported is 4MB. We have some [code in place](https://github.com/10up/classifai/blob/fe28ee7c7971fecdc4de246a5b0beb8b4baf2747/includes/Classifai/Providers/Azure/ComputerVision.php#L742) to return an error if the image size is larger than that so in theory, a 5MB image shouldn't even work, though it sounds like that's not the case.

@dkotter what you're saying is correct and the check we have is working as expected. When we upload an image size > 4MB, the check selects the largest image variant that is < 4MB to process. 

This particular issue is a weird one pertaining to just the `.png` format. From what I am understanding, the AI service takes more time to process a `.png` compared to a `.jpeg`. So, even with a `.png` file which has a size of 3.5MB, it still fails.

This works well when the timeout is increased.

2024-04-02 13:50 UTC, dkotter approved these changes

2024-04-02 13:52 UTC, merged